sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
env:
  global:
  - COVERAGE: false

matrix:
  fast_finish: true
  include:
  # make sure it is running on the oldest supported version
  - php: 7.2
    env: MAGENTO_VERSION=2.3.0
  # fix the code quality check to a specific, but rather new version
  - php: 7.2
    env: MAGENTO_VERSION=2.3.5-p1 CODE_QUALITY=true
  # make sure it is running on the latest version
  - php: 7.2
    env: MAGENTO_VERSION=2.3.1 INTEGRATION_TEST=true
  - php: 7.2
    env: MAGENTO_VERSION=2.3.* INTEGRATION_TEST=true
  - php: 7.3
    env: MAGENTO_VERSION=2.3.3 INTEGRATION_TEST=true
  - php: 7.3
    env: MAGENTO_VERSION=2.3.* INTEGRATION_TEST=true


language: php

cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.php-cs-fixer"
  - "$HOME/.local"

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - "./Test/script/travis_before_install.sh"

install:
  - composer config -g http-basic.repo.magento.com "$MAGENTO_USERNAME" "$MAGENTO_PASSWORD"
  - export MAGENTO_ROOT=`mktemp -d /tmp/mage.XXXXXXXX`
  - "./Test/script/travis_install_magento.sh $MAGENTO_VERSION"

script:
  - "./Test/script/travis_script.sh"
